import { useEffect, useRef, useState } from 'react';

/**
 * TrackingReportModal
 *
 * Displays the output of Agent 4 (Milestone & Execution Tracking Agent).
 * Features:
 *  - Chained from Feasibility, Scope, and Tech Stack agents
 *  - Live overall progress bar & pacing metric
 *  - Interactive milestone checklist: students can mark phases completed
 *  - Detailed deliverables and faculty acceptance criteria
 *  - Faculty review checkpoints timeline
 *  - Export / Print roadmap
 */
export default function TrackingReportModal({ report, project, onClose, onToggleMilestone }) {
  const backdropRef = useRef(null);
  const [activeTab, setActiveTab] = useState('roadmap'); // 'roadmap' | 'checkpoints' | 'actions'
  const [expandedPhase, setExpandedPhase] = useState(null);

  useEffect(() => {
    document.body.style.overflow = 'hidden';
    return () => { document.body.style.overflow = ''; };
  }, []);

  const handleBackdropClick = (e) => {
    if (e.target === backdropRef.current) onClose();
  };

  if (!report) return null;

  const milestones = report.milestones || [];
  const progress = report.overallProgress !== undefined ? report.overallProgress : 0;
  const doneCount = report.milestonesDone !== undefined ? report.milestonesDone : milestones.filter(m => m.completed).length;
  const totalCount = report.totalMilestones || milestones.length || 1;
  const metrics = report.trackingMetrics || {};
  const actions = report.immediateActionItems || [];
  const checkpoints = report.facultyCheckpoints || [];
  const methodology = report.sprintMethodology || '';

  const handleExport = () => {
    const title = project?.title || 'Academic Project';
    const text = [
      `================================================================`,
      `🎓 PROJECT MILESTONE & TRACKING ROADMAP: ${title}`,
      `Generated by ProjectGuide-AI Tracking Agent (Agent 4)`,
      `Overall Progress: ${progress}% (${doneCount}/${totalCount} completed)`,
      `Pace: ${metrics.pace || 'On Schedule'} | Workload: ${metrics.weeklyWorkloadPerStudent || 'N/A'}`,
      `================================================================\n`,
      `METHODOLOGY:\n${methodology}\n`,
      `IMMEDIATE NEXT ACTIONS:\n${actions.map((a, i) => `  ${i + 1}. ${a}`).join('\n')}\n`,
      `MILESTONE PHASES:\n` +
      milestones.map(m => (
        `[${m.completed ? 'COMPLETED' : m.status?.toUpperCase() || 'PENDING'}] ${m.phase}: ${m.title} (${m.weekLabel})\n` +
        `  Description: ${m.description}\n` +
        `  Deliverables:\n${(m.deliverables || []).map(d => `    - ${d}`).join('\n')}\n` +
        `  Acceptance Criteria:\n${(m.acceptanceCriteria || []).map(c => `    * ${c}`).join('\n')}\n`
      )).join('\n'),
      `FACULTY CHECKPOINTS:\n${checkpoints.map((c, i) => `  ${i + 1}. ${c}`).join('\n')}\n`
    ].join('\n');

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.toLowerCase().replace(/[^a-z0-9]/g, '_')}_roadmap.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div
      ref={backdropRef}
      onClick={handleBackdropClick}
      style={{
        position: 'fixed', inset: 0, zIndex: 9999,
        background: 'rgba(0,0,0,0.76)',
        backdropFilter: 'blur(8px)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        padding: '1rem',
      }}
    >
      <div style={{
        background: 'linear-gradient(135deg, #0b1117 0%, #111d24 100%)',
        border: '1px solid rgba(16,185,129,0.3)',
        borderRadius: '1.25rem',
        width: '100%', maxWidth: '820px',
        maxHeight: '92vh', overflowY: 'auto',
        padding: '2rem',
        boxShadow: '0 0 60px rgba(16,185,129,0.12), 0 24px 48px rgba(0,0,0,0.7)',
        scrollbarWidth: 'thin',
        color: '#e2e8f0',
      }}>

        {/* ── Header ── */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1.5rem' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', marginBottom: '0.3rem', flexWrap: 'wrap' }}>
              <span style={{ fontSize: '1.6rem' }}>🗺️</span>
              <h2 style={{ margin: 0, fontSize: '1.35rem', color: '#fff', fontWeight: 700 }}>
                Sprint &amp; Milestone Tracking Roadmap
              </h2>
              {report.aiGenerated && (
                <span style={{
                  padding: '0.2rem 0.6rem', borderRadius: '999px', fontSize: '0.7rem',
                  background: 'rgba(16,185,129,0.15)', color: '#10b981',
                  border: '1px solid rgba(16,185,129,0.35)', fontWeight: 600,
                }}>
                  ✨ AI Generated
                </span>
              )}
            </div>
            <div style={{ fontSize: '0.82rem', color: 'rgba(255,255,255,0.5)' }}>
              {project?.title} · Agent 4 of 4 · Powered by CrewAI + Groq
            </div>
            <div style={{ marginTop: '0.35rem', fontSize: '0.75rem', color: 'rgba(16,185,129,0.85)',
              display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
              <span>🔗</span>
              <span>Chained from Feasibility + Scope + Tech Stack Reports</span>
            </div>
          </div>

          <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
            <button
              onClick={handleExport}
              title="Download text roadmap"
              style={{
                background: 'rgba(16,185,129,0.12)', border: '1px solid rgba(16,185,129,0.3)',
                color: '#10b981', borderRadius: '0.5rem', padding: '0.4rem 0.8rem',
                cursor: 'pointer', fontSize: '0.82rem', fontWeight: 600,
                display: 'flex', alignItems: 'center', gap: '0.3rem'
              }}
            >
              📥 Export
            </button>
            <button
              onClick={onClose}
              style={{
                background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.14)',
                color: '#fff', borderRadius: '0.5rem', padding: '0.4rem 0.8rem',
                cursor: 'pointer', fontSize: '0.85rem',
              }}
            >
              ✕ Close
            </button>
          </div>
        </div>

        {/* ── Progress & Pacing Dashboard Banner ── */}
        <div style={{
          background: 'linear-gradient(135deg, rgba(16,185,129,0.08) 0%, rgba(6,78,59,0.15) 100%)',
          border: '1px solid rgba(16,185,129,0.25)',
          borderRadius: '1rem',
          padding: '1.25rem 1.5rem',
          marginBottom: '1.5rem',
        }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.6rem' }}>
            <div>
              <span style={{ fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: '0.08em', color: 'rgba(255,255,255,0.5)' }}>
                Overall Project Execution
              </span>
              <div style={{ fontSize: '1.4rem', fontWeight: 800, color: '#10b981', marginTop: '0.1rem' }}>
                {progress}% Complete
                <span style={{ fontSize: '0.85rem', fontWeight: 500, color: 'rgba(255,255,255,0.6)', marginLeft: '0.6rem' }}>
                  ({doneCount} of {totalCount} milestones completed)
                </span>
              </div>
            </div>

            <div style={{ display: 'flex', gap: '0.75rem', textAlign: 'right' }}>
              <div style={{ background: 'rgba(0,0,0,0.3)', padding: '0.4rem 0.8rem', borderRadius: '0.5rem', border: '1px solid rgba(255,255,255,0.08)' }}>
                <div style={{ fontSize: '0.68rem', color: 'rgba(255,255,255,0.4)' }}>PACE STATUS</div>
                <div style={{ fontSize: '0.82rem', fontWeight: 600, color: '#34d399' }}>{metrics.pace || 'On Schedule'}</div>
              </div>
              <div style={{ background: 'rgba(0,0,0,0.3)', padding: '0.4rem 0.8rem', borderRadius: '0.5rem', border: '1px solid rgba(255,255,255,0.08)' }}>
                <div style={{ fontSize: '0.68rem', color: 'rgba(255,255,255,0.4)' }}>WORKLOAD</div>
                <div style={{ fontSize: '0.82rem', fontWeight: 600, color: '#38bdf8' }}>{metrics.weeklyWorkloadPerStudent || '10 hrs/wk'}</div>
              </div>
            </div>
          </div>

          {/* Progress bar track */}
          <div style={{
            width: '100%', height: '8px', background: 'rgba(255,255,255,0.1)',
            borderRadius: '999px', overflow: 'hidden', position: 'relative'
          }}>
            <div style={{
              width: `${Math.min(100, Math.max(progress, doneCount > 0 ? (doneCount/totalCount)*100 : 3))}%`,
              height: '100%',
              background: 'linear-gradient(90deg, #10b981 0%, #34d399 100%)',
              boxShadow: '0 0 12px rgba(16,185,129,0.6)',
              transition: 'width 0.4s ease'
            }}></div>
          </div>
        </div>

        {/* ── Navigation Tabs ── */}
        <div style={{ display: 'flex', gap: '0.5rem', borderBottom: '1px solid rgba(255,255,255,0.1)', marginBottom: '1.5rem', paddingBottom: '0.2rem' }}>
          {[
            { key: 'roadmap', label: 'Milestone Roadmap', icon: '📋', count: milestones.length },
            { key: 'actions', label: 'Immediate Next Actions', icon: '⚡', count: actions.length },
            { key: 'checkpoints', label: 'Faculty Checkpoints', icon: '🎯', count: checkpoints.length },
          ].map(tab => (
            <button
              key={tab.key}
              onClick={() => setActiveTab(tab.key)}
              style={{
                background: activeTab === tab.key ? 'rgba(16,185,129,0.15)' : 'transparent',
                border: activeTab === tab.key ? '1px solid rgba(16,185,129,0.35)' : '1px solid transparent',
                color: activeTab === tab.key ? '#34d399' : 'rgba(255,255,255,0.6)',
                borderRadius: '0.5rem',
                padding: '0.45rem 0.9rem',
                cursor: 'pointer',
                fontSize: '0.82rem',
                fontWeight: 600,
                display: 'flex',
                alignItems: 'center',
                gap: '0.4rem',
                transition: 'all 0.15s ease'
              }}
            >
              <span>{tab.icon}</span>
              <span>{tab.label}</span>
              <span style={{
                background: 'rgba(255,255,255,0.08)',
                padding: '0.1rem 0.4rem',
                borderRadius: '999px',
                fontSize: '0.7rem'
              }}>
                {tab.count}
              </span>
            </button>
          ))}
        </div>

        {/* ── TAB 1: MILESTONE ROADMAP ── */}
        {activeTab === 'roadmap' && (
          <div>
            <div style={{ fontSize: '0.78rem', color: 'rgba(255,255,255,0.45)', marginBottom: '0.75rem', display: 'flex', justifyContent: 'space-between' }}>
              <span>Click checkbox to track phase completion. Click phase card to view deliverables.</span>
              <span style={{ color: '#10b981' }}>Sprint Architecture: {metrics.estimatedCompletionWeeks || 4} Weeks</span>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.85rem' }}>
              {milestones.map((m, idx) => {
                const isExpanded = expandedPhase === idx;
                return (
                  <div
                    key={m.id || idx}
                    style={{
                      background: m.completed
                        ? 'rgba(16,185,129,0.05)'
                        : m.status === 'in_progress'
                        ? 'rgba(14,165,233,0.05)'
                        : 'rgba(255,255,255,0.03)',
                      border: m.completed
                        ? '1px solid rgba(16,185,129,0.4)'
                        : m.status === 'in_progress'
                        ? '1px solid rgba(14,165,233,0.35)'
                        : '1px solid rgba(255,255,255,0.08)',
                      borderRadius: '0.85rem',
                      overflow: 'hidden',
                      transition: 'border 0.2s'
                    }}
                  >
                    {/* Phase Header Row */}
                    <div
                      onClick={() => setExpandedPhase(isExpanded ? null : idx)}
                      style={{
                        padding: '1rem 1.25rem',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'space-between',
                        cursor: 'pointer',
                        gap: '1rem'
                      }}
                    >
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.9rem', flex: 1 }}>
                        {/* Interactive Toggle Checkbox */}
                        <div
                          onClick={(e) => {
                            e.stopPropagation();
                            if (onToggleMilestone) {
                              onToggleMilestone(m.id, !m.completed);
                            }
                          }}
                          title={m.completed ? 'Mark as incomplete' : 'Mark as completed'}
                          style={{
                            width: '24px',
                            height: '24px',
                            borderRadius: '6px',
                            border: m.completed ? '2px solid #10b981' : '2px solid rgba(255,255,255,0.3)',
                            background: m.completed ? '#10b981' : 'rgba(0,0,0,0.3)',
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            cursor: 'pointer',
                            flexShrink: 0,
                            transition: 'all 0.15s ease'
                          }}
                        >
                          {m.completed && <span style={{ color: '#fff', fontSize: '0.85rem', fontWeight: 800 }}>✓</span>}
                        </div>

                        <div>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.2rem' }}>
                            <span style={{
                              fontSize: '0.7rem',
                              fontWeight: 700,
                              textTransform: 'uppercase',
                              color: m.completed ? '#10b981' : '#38bdf8',
                              letterSpacing: '0.05em'
                            }}>
                              {m.phase}
                            </span>
                            <span style={{
                              fontSize: '0.7rem',
                              padding: '0.15rem 0.5rem',
                              borderRadius: '999px',
                              background: 'rgba(255,255,255,0.07)',
                              color: 'rgba(255,255,255,0.7)'
                            }}>
                              📅 {m.weekLabel}
                            </span>
                          </div>

                          <div style={{
                            fontSize: '0.92rem',
                            fontWeight: 600,
                            color: m.completed ? 'rgba(255,255,255,0.6)' : '#fff',
                            textDecoration: m.completed ? 'line-through' : 'none'
                          }}>
                            {m.title}
                          </div>
                        </div>
                      </div>

                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                        <span style={{
                          fontSize: '0.72rem',
                          padding: '0.2rem 0.6rem',
                          borderRadius: '999px',
                          fontWeight: 600,
                          background: m.completed ? 'rgba(16,185,129,0.15)' : m.status === 'in_progress' ? 'rgba(14,165,233,0.15)' : 'rgba(255,255,255,0.06)',
                          color: m.completed ? '#34d399' : m.status === 'in_progress' ? '#38bdf8' : 'rgba(255,255,255,0.4)',
                          border: m.completed ? '1px solid rgba(16,185,129,0.3)' : m.status === 'in_progress' ? '1px solid rgba(14,165,233,0.3)' : '1px solid rgba(255,255,255,0.1)'
                        }}>
                          {m.completed ? 'Completed' : m.status === 'in_progress' ? 'In Progress' : 'Pending'}
                        </span>
                        <span style={{ fontSize: '0.8rem', color: 'rgba(255,255,255,0.4)' }}>
                          {isExpanded ? '▲' : '▼'}
                        </span>
                      </div>
                    </div>

                    {/* Phase Details (Expandable) */}
                    {isExpanded && (
                      <div style={{
                        padding: '0.5rem 1.25rem 1.25rem 3.4rem',
                        borderTop: '1px solid rgba(255,255,255,0.06)',
                        background: 'rgba(0,0,0,0.2)'
                      }}>
                        <p style={{ fontSize: '0.82rem', color: 'rgba(255,255,255,0.75)', lineHeight: 1.5, margin: '0.5rem 0 0.8rem 0' }}>
                          {m.description}
                        </p>

                        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '1rem' }}>
                          {/* Deliverables */}
                          <div style={{ background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: '0.5rem', padding: '0.75rem' }}>
                            <div style={{ fontSize: '0.7rem', fontWeight: 700, color: '#38bdf8', textTransform: 'uppercase', marginBottom: '0.4rem' }}>
                              📦 Concrete Deliverables
                            </div>
                            <ul style={{ margin: 0, paddingLeft: '1.1rem', fontSize: '0.78rem', color: 'rgba(255,255,255,0.85)', lineHeight: 1.5 }}>
                              {(m.deliverables || []).map((d, dIdx) => (
                                <li key={dIdx} style={{ marginBottom: '0.25rem' }}>{d}</li>
                              ))}
                            </ul>
                          </div>

                          {/* Acceptance Criteria */}
                          <div style={{ background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: '0.5rem', padding: '0.75rem' }}>
                            <div style={{ fontSize: '0.7rem', fontWeight: 700, color: '#10b981', textTransform: 'uppercase', marginBottom: '0.4rem' }}>
                              ✅ Faculty Acceptance Criteria
                            </div>
                            <ul style={{ margin: 0, paddingLeft: '1.1rem', fontSize: '0.78rem', color: 'rgba(255,255,255,0.85)', lineHeight: 1.5 }}>
                              {(m.acceptanceCriteria || []).map((c, cIdx) => (
                                <li key={cIdx} style={{ marginBottom: '0.25rem' }}>{c}</li>
                              ))}
                            </ul>
                          </div>
                        </div>

                        {/* Metadata pills */}
                        <div style={{ display: 'flex', gap: '0.75rem', marginTop: '0.8rem', fontSize: '0.72rem', color: 'rgba(255,255,255,0.45)' }}>
                          <span>⏱️ Est. Effort: {m.estimatedEffortHours || 24} hours</span>
                          {m.dependencies && m.dependencies.length > 0 && (
                            <span>🔗 Prerequisite: {m.dependencies.join(', ')}</span>
                          )}
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* ── TAB 2: IMMEDIATE NEXT ACTIONS ── */}
        {activeTab === 'actions' && (
          <div>
            <div style={{ fontSize: '0.78rem', color: 'rgba(255,255,255,0.45)', marginBottom: '1rem' }}>
              Sprint kickoff guidance: Tackle these 3 immediate action items before the first milestone deadline.
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', marginBottom: '1.5rem' }}>
              {actions.map((act, i) => (
                <div key={i} style={{
                  background: 'rgba(255,255,255,0.04)',
                  border: '1px solid rgba(16,185,129,0.2)',
                  borderRadius: '0.75rem',
                  padding: '1rem 1.25rem',
                  display: 'flex',
                  alignItems: 'flex-start',
                  gap: '0.85rem'
                }}>
                  <div style={{
                    width: '26px', height: '26px', borderRadius: '50%',
                    background: 'rgba(16,185,129,0.2)', color: '#34d399',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    fontWeight: 700, fontSize: '0.8rem', flexShrink: 0, marginTop: '0.1rem'
                  }}>
                    {i + 1}
                  </div>
                  <div style={{ fontSize: '0.88rem', color: 'rgba(255,255,255,0.9)', lineHeight: 1.5 }}>
                    {act}
                  </div>
                </div>
              ))}
            </div>

            {methodology && (
              <div style={{
                background: 'rgba(255,255,255,0.02)',
                border: '1px solid rgba(255,255,255,0.08)',
                borderRadius: '0.75rem',
                padding: '1rem 1.25rem'
              }}>
                <div style={{ fontSize: '0.72rem', textTransform: 'uppercase', color: 'rgba(255,255,255,0.4)', fontWeight: 700, marginBottom: '0.4rem' }}>
                  Agile Sprint Methodology
                </div>
                <div style={{ fontSize: '0.84rem', color: 'rgba(255,255,255,0.75)', lineHeight: 1.5 }}>
                  {methodology}
                </div>
              </div>
            )}
          </div>
        )}

        {/* ── TAB 3: FACULTY CHECKPOINTS ── */}
        {activeTab === 'checkpoints' && (
          <div>
            <div style={{ fontSize: '0.78rem', color: 'rgba(255,255,255,0.45)', marginBottom: '1rem' }}>
              Formal institutional review gates to pass before external viva and grading.
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.85rem' }}>
              {checkpoints.map((cp, idx) => (
                <div key={idx} style={{
                  background: 'rgba(255,255,255,0.03)',
                  border: '1px solid rgba(56,189,248,0.2)',
                  borderRadius: '0.75rem',
                  padding: '1rem 1.25rem',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.85rem'
                }}>
                  <span style={{ fontSize: '1.25rem' }}>🎯</span>
                  <div style={{ fontSize: '0.88rem', color: 'rgba(255,255,255,0.85)', lineHeight: 1.5 }}>
                    {cp}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ── Footer ── */}
        <div style={{
          marginTop: '2rem',
          paddingTop: '1rem',
          borderTop: '1px solid rgba(255,255,255,0.08)',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          fontSize: '0.78rem',
          color: 'rgba(255,255,255,0.4)'
        }}>
          <div>💡 Tip: Mark deliverables as completed to update your faculty guide in real-time.</div>
          <button
            onClick={onClose}
            style={{
              background: 'rgba(255,255,255,0.08)',
              border: '1px solid rgba(255,255,255,0.15)',
              color: '#fff',
              borderRadius: '0.5rem',
              padding: '0.45rem 1rem',
              cursor: 'pointer',
              fontWeight: 600
            }}
          >
            Done
          </button>
        </div>

      </div>
    </div>
  );
}
