export const SKILLS = [
  { id: 'python',     name: 'Python',                icon: '🐍' },
  { id: 'javascript', name: 'JavaScript',             icon: '🟨' },
  { id: 'java',       name: 'Java',                   icon: '☕' },
  { id: 'c_cpp',      name: 'C / C++',                icon: '⚙️' },
  { id: 'react',      name: 'React / Next.js',        icon: '⚛️' },
  { id: 'nodejs',     name: 'Node.js / Express',      icon: '🟢' },
  { id: 'webdev',     name: 'HTML / CSS',             icon: '🌐' },
  { id: 'ml',         name: 'Machine Learning',       icon: '🤖' },
  { id: 'dl',         name: 'Deep Learning',          icon: '🧠' },
  { id: 'nlp',        name: 'NLP / LLMs',             icon: '💬' },
  { id: 'cv',         name: 'Computer Vision',        icon: '👁️' },
  { id: 'ds',         name: 'Data Science / Analysis',icon: '📊' },
  { id: 'dbms',       name: 'SQL / Databases',        icon: '🗄️' },
  { id: 'mongodb',    name: 'NoSQL / MongoDB',        icon: '🍃' },
  { id: 'android',    name: 'Android Development',    icon: '📱' },
  { id: 'flutter',    name: 'Flutter / React Native', icon: '💙' },
  { id: 'cloud',      name: 'Cloud / AWS / GCP',      icon: '☁️' },
  { id: 'devops',     name: 'DevOps / Docker / CI-CD',icon: '🔧' },
  { id: 'iot',        name: 'IoT / Embedded Systems', icon: '🔌' },
  { id: 'cyber',      name: 'Cybersecurity / Networking', icon: '🔒' },
  { id: 'dsa',        name: 'Data Structures & Algorithms', icon: '🧩' },
  { id: 'os',         name: 'Operating Systems',      icon: '🖥️' },
  { id: 'blockchain', name: 'Blockchain / Web3',      icon: '🔗' },
  { id: 'git',        name: 'Git / Version Control',  icon: '🗂️' },
];

export const LEVEL_LABELS = ['', 'Beginner', 'Basic', 'Intermediate', 'Advanced', 'Expert'];

export const DOMAINS = [
  { id: 'aiml',        name: 'AI / Machine Learning', icon: '🤖' },
  { id: 'web',         name: 'Web Development',       icon: '🌐' },
  { id: 'mobile',      name: 'Mobile Apps',           icon: '📱' },
  { id: 'ds',          name: 'Data Science',          icon: '📊' },
  { id: 'iot',         name: 'IoT & Embedded',        icon: '🔌' },
  { id: 'cyber',       name: 'Cybersecurity',         icon: '🔒' },
  { id: 'cloud',       name: 'Cloud Computing',       icon: '☁️' },
  { id: 'blockchain',  name: 'Blockchain',            icon: '🔗' },
  { id: 'arvr',        name: 'AR / VR',               icon: '🥽' },
  { id: 'robotics',    name: 'Robotics',              icon: '🦾' },
  { id: 'gamedev',     name: 'Game Development',      icon: '🎮' },
  { id: 'nlp',         name: 'NLP / Chatbots',        icon: '💬' },
  { id: 'fintech',     name: 'FinTech',               icon: '💳' },
  { id: 'healthcare',  name: 'Healthcare Tech',       icon: '🏥' },
  { id: 'edtech',      name: 'EdTech',                icon: '📚' },
  { id: 'automation',  name: 'Automation / Scripting',icon: '⚡' },
];
